// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VladimirNyaninKT_31_22.Database;

#nullable disable

namespace VladimirNyaninKT_31_22.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20251207112926_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VladimirNyaninKT_31_22.Models.Degree", b =>
                {
                    b.Property<int>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("degree_id")
                        .HasComment("Идентификатор учёной степени");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DegreeId"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bool")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаления");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("degree_name")
                        .HasComment("Название учёной степени");

                    b.HasKey("DegreeId")
                        .HasName("pk_degrees_degree_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_degrees_is_deleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_degrees_degree_name");

                    b.ToTable("degrees", (string)null);
                });

            modelBuilder.Entity("VladimirNyaninKT_31_22.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("department_id")
                        .HasComment("Идентификатор кафедры");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bool")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаления");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("department_name")
                        .HasComment("Название кафедры");

                    b.HasKey("DepartmentId")
                        .HasName("pk_departments_department_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_departments_is_deleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_departments_department_name");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("VladimirNyaninKT_31_22.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("position_id")
                        .HasComment("Идентификатор должности");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PositionId"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bool")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаления");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("position_name")
                        .HasComment("Название должности");

                    b.HasKey("PositionId")
                        .HasName("pk_positions_position_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_positions_is_deleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_positions_position_name");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("VladimirNyaninKT_31_22.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subject_id")
                        .HasComment("Идентификатор дисциплины");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectId"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bool")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаления");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("subject_name")
                        .HasComment("Название дисциплины");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkloadId")
                        .HasColumnType("integer");

                    b.HasKey("SubjectId")
                        .HasName("pk_subjects_subject_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_subjects_is_deleted");

                    b.HasIndex("TeacherId");

                    b.HasIndex("WorkloadId");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("VladimirNyaninKT_31_22.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id")
                        .HasComment("Идентификатор преподавателя");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeacherId"));

                    b.Property<int>("DegreeId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("teacher_first_name")
                        .HasComment("Имя преподавателя");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bool")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаления");

                    b.Property<bool>("IsHead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bool")
                        .HasDefaultValue(false)
                        .HasColumnName("is_head")
                        .HasComment("Признак заведующего кафедрой");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("teacher_last_name")
                        .HasComment("Фамилия преподавателя");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("teacher_patronymic")
                        .HasComment("Отчество преподавателя");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.HasKey("TeacherId")
                        .HasName("pk_teachers_teacher_id");

                    b.HasIndex("DegreeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("ix_teachers_teacher_first_name");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_teachers_is_deleted");

                    b.HasIndex("IsHead")
                        .HasDatabaseName("ix_teachers_is_head");

                    b.HasIndex("LastName")
                        .HasDatabaseName("ix_teachers_teacher_last_name");

                    b.HasIndex("Patronymic")
                        .HasDatabaseName("ix_teachers_teacher_patronymic");

                    b.HasIndex("PositionId");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("VladimirNyaninKT_31_22.Models.Workload", b =>
                {
                    b.Property<int>("WorkloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("workload_id")
                        .HasComment("Идентификатор загруженности");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkloadId"));

                    b.Property<int>("HoursQuantity")
                        .HasColumnType("int4")
                        .HasColumnName("hours_quantity")
                        .HasComment("Загруженность в часах");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bool")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаления");

                    b.HasKey("WorkloadId")
                        .HasName("pk_workloads_workload_id");

                    b.HasIndex("HoursQuantity")
                        .IsUnique()
                        .HasDatabaseName("uk_workloads_hours_quantity");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_workloads_is_deleted");

                    b.ToTable("workloads", (string)null);
                });

            modelBuilder.Entity("VladimirNyaninKT_31_22.Models.Subject", b =>
                {
                    b.HasOne("VladimirNyaninKT_31_22.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subjects_teacher_id");

                    b.HasOne("VladimirNyaninKT_31_22.Models.Workload", "Workload")
                        .WithMany()
                        .HasForeignKey("WorkloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subjects_workload_id");

                    b.Navigation("Teacher");

                    b.Navigation("Workload");
                });

            modelBuilder.Entity("VladimirNyaninKT_31_22.Models.Teacher", b =>
                {
                    b.HasOne("VladimirNyaninKT_31_22.Models.Degree", "Degree")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_degree_id");

                    b.HasOne("VladimirNyaninKT_31_22.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_department_id");

                    b.HasOne("VladimirNyaninKT_31_22.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_position_id");

                    b.Navigation("Degree");

                    b.Navigation("Department");

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
